{{ if .linux }}
[".local/bin/antigen.zsh"]
  type = "file"
  url = "https://git.io/antigen"
[".local/bin/starship"]
  type = "archive"
  url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
[".local/bin/iterm2_shell_integration.bash"]
  type = "file"
  url = "https://iterm2.com/shell_integration/bash"
[".local/bin/iterm2_shell_integration.zsh"]
  type = "file"
  url = "https://iterm2.com/shell_integration/zsh"
{{ end }}
{{ if .mac }}
[".local/bin/imgcat"]
  type = "file"
  url = "https://iterm2.com/utilities/imgcat"
  executable = true
{{ end }}

{{ if .shared }}
[".local/bin/kubectx"]
  type = "archive"
  url = "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_x86_64.tar.gz"
[".local/bin/stern"]
  type = "file"
  url = "https://github.com/wercker/stern/releases/latest/download/stern_linux_amd64"
  executable = true
{{ end }}
